[unix_http_server]
#file=/var/run/ pose problème dans file=/var/run/supervisor.sock
#car /var/run/ appartient à root.
#L'utilisateur user (uid 1000) n'a pas le droit d'y créer un fichier
#socket Unix pour supervisorctl - bypass du path par défaut dans /var/run/
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
#serverurl=unix:///var/run/supervisor.sock
serverurl=unix:///tmp/supervisor.sock

# Activer l'interface de contrôle XML-RPC que supervisorctl utilise pour communiquer avec supervisord
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
nodaemon=true
user=user
logfile=/home/user/logs/supervisord.log
logfile_maxbytes=10MB
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/home/user/logs/nginx/access.log
stderr_logfile=/home/user/logs/nginx/error.log
priority=10

[program:fastapi]
command=uvicorn api.src.fastapi:app --host 0.0.0.0 --port %(ENV_PORT_FASTAPI_EXPOSED)s --reload
directory=/home/user/app
autostart=true
autorestart=true
stdout_logfile=/home/user/logs/fastapi.log
stderr_logfile=/home/user/logs/fastapi_err.log
priority=20

[program:streamlit]
command=streamlit run streamlit/src/dashboard.py --server.address=%(ENV_STREAMLIT_SERVER_ADDRESS)s --server.port=%(ENV_PORT_STREAMLIT_EXPOSED)s --server.baseUrlPath=%(ENV_STREAMLIT_SERVER_BASE_URL_PATH)s
directory=/home/user/app
autostart=true
autorestart=true
stdout_logfile=/home/user/logs/streamlit/streamlit.log
stderr_logfile=/home/user/logs/streamlit/streamlit_err.log
priority=30